//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime creation_date { get; set; }
        public int language_id { get; set; }
    
        public virtual tb_language tb_language { get; set; }
    }
}
